from app import db
from app.models import Card, Job, Vehicle, House

# Regular cards
c = Card(regular=True, text="Volunteer as crossing guard", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Donate to goodwill", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Volunteer at soup kitchen", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Read to local senior citizens", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Coach children's sports team", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Take an art class", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Learn new language", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Learn new skill", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Learn to play instrument", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Learn new recipe", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Go camping", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Sew blankets for the homeless", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Make emergency preparedness plan", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Plant a garden", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Join a gym", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Help a friend move", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Bad hair day", affects_points=True, amount=-50)
db.session.add(c)
c = Card(regular=True, text="Family issue", affects_points=False, amount=-5000)
db.session.add(c)
c = Card(regular=True, text="Mugged", affects_points=True, amount=-250)
db.session.add(c)
c = Card(regular=True, text="Mental illness", affects_points=False, amount=-5000)
db.session.add(c)
c = Card(regular=True, text="Stuck in traffic", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Stuck in traffic", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Stuck in traffic", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Stuck in traffic", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Win lottery", affects_points=False, amount=100000)
db.session.add(c)
c = Card(regular=True, text="Garage sale", affects_points=False, amount=500)
db.session.add(c)
c = Card(regular=True, text="Sell items on eBay", affects_points=False, amount=1000)
db.session.add(c)
c = Card(regular=True, text="Donate to charity", affects_points=False, amount=500)
db.session.add(c)
c = Card(regular=True, text="Car accident", affects_points=False, amount=-50000)
db.session.add(c)
c = Card(regular=True, text="Earthquake damage", affects_points=False, amount=-50000)
db.session.add(c)
c = Card(regular=True, text="Fire damage", affects_points=False, amount=-50000)
db.session.add(c)
c = Card(regular=True, text="Pest problem", affects_points=False, amount=-5000)
db.session.add(c)
c = Card(regular=True, text="Tech problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Tech problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Tech problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Tech problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Tech problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Lawsuit", affects_points=False, amount=-500)
db.session.add(c)
c = Card(regular=True, text="Speeding", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Speeding", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Speeding", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Speeding", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Speeding", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Minor medical problems", affects_points=False, amount=-50)
db.session.add(c)
c = Card(regular=True, text="Major medical problems", affects_points=False, amount=-50000)
db.session.add(c)
c = Card(regular=True, text="Minor medical problems", affects_points=False, amount=-150)
db.session.add(c)
c = Card(regular=True, text="Major medical problems", affects_points=False, amount=-100000)
db.session.add(c)
c = Card(regular=True, text="Car repairs", affects_points=False, amount=-500)
db.session.add(c)
c = Card(regular=True, text="Found money", affects_points=False, amount=100)
db.session.add(c)
c = Card(regular=True, text="Lost your phone", affects_points=True, amount=-250)
db.session.add(c)
c = Card(regular=True, text="Take martial arts class", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Take swimming class", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Take photography class", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Baker releases cookbook", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Baker holds bake sale", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Baker opens new bakery", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Animal trainer wins pet competition", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Animal trainer does pet food commercial", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Animal trainer does county fair show", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Reporter writes breaking news story", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Reporter writes breaking news story", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Author writes best-selling novel", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Author writes best-selling novel", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Singer performs at concert", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Actor has a new movie out", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Engineer creates a new invention", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Athlete wins championship", affects_points=False, amount=-10)
db.session.add(c)
c = Card(regular=True, text="Lose job", affects_points=False, amount=0)
db.session.add(c)
c = Card(regular=True, text="Lose job", affects_points=False, amount=0)
db.session.add(c)
c = Card(regular=True, text="Birthday party", affects_points=False, amount=-20)
db.session.add(c)
c = Card(regular=True, text="Birthday party", affects_points=False, amount=-20)
db.session.add(c)
c = Card(regular=True, text="Graduation party", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Graduation party", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Anniversary party", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Anniversary party", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=True, text="Work dinner", affects_points=False, amount=-50)
db.session.add(c)
c = Card(regular=True, text="Work dinner", affects_points=False, amount=-50)
db.session.add(c)
c = Card(regular=True, text="Wedding", affects_points=False, amount=-150)
db.session.add(c)
c = Card(regular=True, text="Wedding", affects_points=False, amount=-150)
db.session.add(c)
c = Card(regular=True, text="Run a marathon", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Go scuba diving", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Go skiing", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go hiking", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go horseback riding", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go skydiving", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Go mountain climbing", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Do karaoke", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Hot air balloon ride", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Stargaze", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go on a picnic", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go to museum", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go to zoo", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Donate blood", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=True, text="Go bowling", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go roller skating", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Play mini golf", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go birdwatching", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Go kayaking", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Have movie marathon", affects_points=True, amount=25)
db.session.add(c)
c = Card(regular=True, text="Forgot a birthday", affects_points=True, amount=50)
db.session.add(c)

# College cards
c = Card(regular=False, text="Go to career fair", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Go to conference", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Study Abroad", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Learn to budget", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Join a campus club", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Make Dean's List", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Summer internship", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Attend Homecoming celebration", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Make new friends", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Volunteer at animal shelter", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Volunteer at hospital", affects_points=True, amount=50)
db.session.add(c)
c = Card(regular=False, text="Bad roommate", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Pull an all-nighter", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Dumped by significant other", affects_points=True, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Required class is full", affects_points=True, amount=-250)
db.session.add(c)
c = Card(regular=False, text="Bed bugs in dorm", affects_points=True, amount=-250)
db.session.add(c)
c = Card(regular=False, text="Fail exam", affects_points=True, amount=-500)
db.session.add(c)
c = Card(regular=False, text="Sell used textbooks", affects_points=False, amount=100)
db.session.add(c)
c = Card(regular=False, text="Babysit", affects_points=False, amount=5000)
db.session.add(c)
c = Card(regular=False, text="Lifeguard", affects_points=False, amount=5000)
db.session.add(c)
c = Card(regular=False, text="Tutoring", affects_points=False, amount=5000)
db.session.add(c)
c = Card(regular=False, text="Go to amusement park", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Go to beach", affects_points=False, amount=-50)
db.session.add(c)
c = Card(regular=False, text="Buy school spirit gear", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Buy school supplies", affects_points=False, amount=-50)
db.session.add(c)
c = Card(regular=False, text="Buy textbooks", affects_points=False, amount=-150)
db.session.add(c)
c = Card(regular=False, text="Slept in; missed class", affects_points=True, amount=-50)
db.session.add(c)
c = Card(regular=False, text="Minor medical problems", affects_points=False, amount=-100)
db.session.add(c)
c = Card(regular=False, text="Major medical problems", affects_points=False, amount=-75000)
db.session.add(c)

# Vehicles
v = Vehicle(category="no-family", name="Skateboard", cost=100, insurance=0, gas=0, sell_price=100)
db.session.add(v)
v = Vehicle(category="no-family", name="Bike", cost=1000, insurance=0, gas=0, sell_price=0)
db.session.add(v)
v = Vehicle(category="no-family", name="Public Transit", cost=2000, insurance=0, gas=0, sell_price=0)
db.session.add(v)
v = Vehicle(category="small-family", name="Mini", cost=20000, insurance=600, gas=1000, sell_price=10000)
db.session.add(v)
v = Vehicle(category="small-family", name="Sedan", cost=30000, insurance=900, gas=1500, sell_price=15000)
db.session.add(v)
v = Vehicle(category="small-family", name="Station Wagon", cost=30000, insurance=900, gas=1500, sell_price=15000)
db.session.add(v)
v = Vehicle(category="small-family", name="Hatchback", cost=30000, insurance=900, gas=1500, sell_price=15000)
db.session.add(v)
v = Vehicle(category="large-family", name="Pickup Truck", cost=40000, insurance=1200, gas=2000, sell_price=20000)
db.session.add(v)
v = Vehicle(category="large-family", name="SUV", cost=40000, insurance=1200, gas=2000, sell_price=20000)
db.session.add(v)
v = Vehicle(category="large-family", name="Minivan", cost=40000, insurance=1200, gas=2000, sell_price=20000)
db.session.add(v)
v = Vehicle(category="large-family", name="Convertible", cost=50000, insurance=1500, gas=2500, sell_price=25000)
db.session.add(v)
v = Vehicle(category="large-family", name="Hybrid", cost=50000, insurance=1500, gas=1000, sell_price=25000)
db.session.add(v)
v = Vehicle(category="large-family", name="Electric Car", cost=60000, insurance=1800, gas=0, sell_price=30000)
db.session.add(v)
v = Vehicle(category="large-family", name="Sports Car", cost=80000, insurance=2400, gas=4000, sell_price=40000)
db.session.add(v)
v = Vehicle(category="large-family", name="Tesla", cost=100000, insurance=3000, gas=0, sell_price=50000)
db.session.add(v)
v = Vehicle(category="large-family", name="Limo", cost=100000, insurance=3000, gas=5000, sell_price=50000)
db.session.add(v)

# Houses
h = House(category="no-family", name="Teepee", cost=1000, minus_points=28, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="no-family", name="Tent", cost=2000, minus_points=20, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="no-family", name="Igloo", cost=3000, minus_points=15, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="no-family", name="Hut", cost=3000, minus_points=15, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="no-family", name="Tree House", cost=5000, minus_points=8, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="no-family", name="Studio", cost=7000, minus_points=1, insurance=0, maid=0, sell_price=0)
db.session.add(h)
h = House(category="small-family", name="Mobile Home", cost=80000, minus_points=60, insurance=160, maid=0, sell_price=96000)
db.session.add(h)
h = House(category="small-family", name="Bungalow", cost=80000, minus_points=60, insurance=160, maid=0, sell_price=96000)
db.session.add(h)
h = House(category="small-family", name="Cottage", cost=90000, minus_points=50, insurance=180, maid=0, sell_price=108000)
db.session.add(h)
h = House(category="small-family", name="Apartment", cost=90000, minus_points=50, insurance=180, maid=0, sell_price=108000)
db.session.add(h)
h = House(category="small-family", name="Condo", cost=100000, minus_points=40, insurance=200, maid=0, sell_price=120000)
db.session.add(h)
h = House(category="small-family", name="Log Cabin", cost=120000, minus_points=30, insurance=240, maid=0, sell_price=144000)
db.session.add(h)
h = House(category="large-family", name="Houseboat", cost=200000, minus_points=120, insurance=400, maid=1000, sell_price=260000)
db.session.add(h)
h = House(category="large-family", name="Ranch", cost=350000, minus_points=110, insurance=700, maid=1750, sell_price=455000)
db.session.add(h)
h = House(category="large-family", name="Snowy Chalet", cost=500000, minus_points=100, insurance=1000, maid=2500, sell_price=650000)
db.session.add(h)
h = House(category="large-family", name="Penthouse", cost=600000, minus_points=90, insurance=1200, maid=3000, sell_price=780000)
db.session.add(h)
h = House(category="large-family", name="Mansion", cost=800000, minus_points=80, insurance=1600, maid=4000, sell_price=1040000)
db.session.add(h)
h = House(category="large-family", name="Castle", cost=1000000, minus_points=70, insurance=2000, maid=5000, sell_price=1300000)
db.session.add(h)

# Jobs
j = Job(category="military",  title="Military", base_salary=5000, default_time_til_raise=4)
db.session.add(j)
j = Job(category="regular",  title="YouTuber", base_salary=15000, default_time_til_raise=0)
db.session.add(j)
j = Job(category="job-in-college",  title="Cashier", base_salary=10000, default_time_til_raise=0)
db.session.add(j)
j = Job(category="job-in-college",  title="Barista", base_salary=10000, default_time_til_raise=0)
db.session.add(j)
j = Job(category="job-in-college",  title="Waiter", base_salary=13000, default_time_til_raise=0)
db.session.add(j)
j = Job(category="job-in-college",  title="Janitor", base_salary=15000, default_time_til_raise=0)
db.session.add(j)
j = Job(category="regular",  title="Hair Stylist", base_salary=25000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Baker", base_salary=30000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Dog Trainer", base_salary=30000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Exterminator", base_salary=35000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Mechanic", base_salary=40000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Plumber", base_salary=40000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="grad-school-1",  title="Teacher", base_salary=40000, default_time_til_raise=1)
db.session.add(j)
j = Job(category="regular",  title="Reporter", base_salary=45000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Carpenter", base_salary=50000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Truck Driver", base_salary=50000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Firefighter", base_salary=50000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Flight Attendant", base_salary=50000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="college-grad",  title="Electrician", base_salary=50000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Police Officer", base_salary=60000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="college-grad",  title="Accountant", base_salary=60000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="college-grad",  title="Author", base_salary=60000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="grad-school-2",  title="Chiropractor", base_salary=70000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="college-grad",  title="Psychologist", base_salary=70000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Farmer", base_salary=75000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Realtor", base_salary=80000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="grad-school-1",  title="Veterinarian", base_salary=80000, default_time_til_raise=2)
db.session.add(j)
j = Job(category="regular",  title="Athlete", base_salary=100000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="regular",  title="Singer", base_salary=100000, default_time_til_raise=3)
j = Job(category="regular",  title="Actor", base_salary=100000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="college-grad",  title="Programmer", base_salary=100000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="college-grad",  title="Engineer", base_salary=100000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="grad-school-1",  title="Pilot", base_salary=100000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="grad-school-2",  title="Lawyer", base_salary=150000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="grad-school-2",  title="Dentist", base_salary=170000, default_time_til_raise=3)
db.session.add(j)
j = Job(category="grad-school-6",  title="Doctor", base_salary=300000, default_time_til_raise=4)
db.session.add(j)

db.session.commit()
