"""empty message

Revision ID: e8ce92aad488
Revises: 
Create Date: 2020-07-21 09:53:43.198162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ce92aad488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regular', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('affects_points', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_regular'), 'card', ['regular'], unique=False)
    op.create_index(op.f('ix_card_text'), 'card', ['text'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('roll_order', sa.Boolean(), nullable=True),
    sa.Column('ready_to_start', sa.Boolean(), nullable=True),
    sa.Column('cur_turn', sa.Integer(), nullable=True),
    sa.Column('num_players', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_date_finished'), 'game', ['date_finished'], unique=False)
    op.create_index(op.f('ix_game_date_started'), 'game', ['date_started'], unique=False)
    op.create_index(op.f('ix_game_finished'), 'game', ['finished'], unique=False)
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('minus_points', sa.Integer(), nullable=True),
    sa.Column('insurance', sa.Integer(), nullable=True),
    sa.Column('maid', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_category'), 'house', ['category'], unique=False)
    op.create_index(op.f('ix_house_name'), 'house', ['name'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('picked', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('base_salary', sa.Integer(), nullable=True),
    sa.Column('default_time_til_raise', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_category'), 'job', ['category'], unique=False)
    op.create_index(op.f('ix_job_picked'), 'job', ['picked'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('insurance', sa.Integer(), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_category'), 'vehicle', ['category'], unique=False)
    op.create_index(op.f('ix_vehicle_name'), 'vehicle', ['name'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('cur_game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cur_game'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=True)
    op.create_table('player__info',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('turn_num', sa.Integer(), nullable=True),
    sa.Column('last_card', sa.String(length=140), nullable=True),
    sa.Column('done_action', sa.Boolean(), nullable=True),
    sa.Column('jobs_page_type', sa.String(length=20), nullable=True),
    sa.Column('notes1', sa.String(length=255), nullable=True),
    sa.Column('notes2', sa.String(length=255), nullable=True),
    sa.Column('notes3', sa.String(length=255), nullable=True),
    sa.Column('notes4', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=20), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('num_pay_raises', sa.Integer(), nullable=True),
    sa.Column('cur_time_til_raise', sa.Integer(), nullable=True),
    sa.Column('current_salary', sa.Integer(), nullable=True),
    sa.Column('age_grad', sa.Integer(), nullable=True),
    sa.Column('grad_school', sa.Boolean(), nullable=True),
    sa.Column('graduating', sa.Boolean(), nullable=True),
    sa.Column('car', sa.String(length=64), nullable=True),
    sa.Column('old_car', sa.String(length=64), nullable=True),
    sa.Column('house', sa.String(length=64), nullable=True),
    sa.Column('old_house', sa.String(length=64), nullable=True),
    sa.Column('married', sa.Boolean(), nullable=True),
    sa.Column('num_kids', sa.Integer(), nullable=True),
    sa.Column('oldest_child_age', sa.Integer(), nullable=True),
    sa.Column('have_auto_ins', sa.Boolean(), nullable=True),
    sa.Column('last_auto_ins', sa.Integer(), nullable=True),
    sa.Column('have_health_ins', sa.Boolean(), nullable=True),
    sa.Column('have_home_ins', sa.Boolean(), nullable=True),
    sa.Column('last_home_ins', sa.Integer(), nullable=True),
    sa.Column('have_pet', sa.Boolean(), nullable=True),
    sa.Column('college_loans', sa.Integer(), nullable=True),
    sa.Column('loans', sa.Integer(), nullable=True),
    sa.Column('buying_organic', sa.Boolean(), nullable=True),
    sa.Column('was_janitor', sa.Boolean(), nullable=True),
    sa.Column('med_prob', sa.Boolean(), nullable=True),
    sa.Column('depressed', sa.Boolean(), nullable=True),
    sa.Column('yrs_military', sa.Integer(), nullable=True),
    sa.Column('yrs_til_buy_organic', sa.Integer(), nullable=True),
    sa.Column('bought_appliances', sa.Boolean(), nullable=True),
    sa.Column('yrs_til_upgrade_appliances', sa.Integer(), nullable=True),
    sa.Column('yrs_til_change_car', sa.Integer(), nullable=True),
    sa.Column('yrs_til_change_house', sa.Integer(), nullable=True),
    sa.Column('yrs_til_buy_clothes', sa.Integer(), nullable=True),
    sa.Column('yrs_til_travel', sa.Integer(), nullable=True),
    sa.Column('yrs_til_change_married', sa.Integer(), nullable=True),
    sa.Column('yrs_til_have_kid', sa.Integer(), nullable=True),
    sa.Column('yrs_til_have_grandkid', sa.Integer(), nullable=True),
    sa.Column('yrs_til_switch_jobs', sa.Integer(), nullable=True),
    sa.Column('yrs_til_rich_action', sa.Integer(), nullable=True),
    sa.Column('have_pool', sa.Boolean(), nullable=True),
    sa.Column('major_donor', sa.Boolean(), nullable=True),
    sa.Column('yrs_til_peace_corps', sa.Integer(), nullable=True),
    sa.Column('yrs_til_mission_trip', sa.Integer(), nullable=True),
    sa.Column('yrs_til_invest', sa.Integer(), nullable=True),
    sa.Column('upgrade_over_40', sa.Integer(), nullable=True),
    sa.Column('num_yrs_teacher', sa.Integer(), nullable=True),
    sa.Column('mil_to_college', sa.Boolean(), nullable=True),
    sa.Column('mil_start_college', sa.Integer(), nullable=True),
    sa.Column('need_loan', sa.Boolean(), nullable=True),
    sa.Column('num_times_travel', sa.Integer(), nullable=True),
    sa.Column('num_times_buy_organic', sa.Integer(), nullable=True),
    sa.Column('num_times_invest', sa.Integer(), nullable=True),
    sa.Column('num_times_buy_clothes', sa.Integer(), nullable=True),
    sa.Column('num_times_peace_corps', sa.Integer(), nullable=True),
    sa.Column('num_times_season_tickets', sa.Integer(), nullable=True),
    sa.Column('num_times_backpacking', sa.Integer(), nullable=True),
    sa.Column('num_times_mission_trip', sa.Integer(), nullable=True),
    sa.Column('total_taxes', sa.Integer(), nullable=True),
    sa.Column('total_insurance', sa.Integer(), nullable=True),
    sa.Column('total_shopping', sa.Integer(), nullable=True),
    sa.Column('total_car_maintenance', sa.Integer(), nullable=True),
    sa.Column('total_maid', sa.Integer(), nullable=True),
    sa.Column('total_utilities', sa.Integer(), nullable=True),
    sa.Column('total_dental', sa.Integer(), nullable=True),
    sa.Column('total_eat_ent', sa.Integer(), nullable=True),
    sa.Column('total_gas', sa.Integer(), nullable=True),
    sa.Column('total_tax_prep', sa.Integer(), nullable=True),
    sa.Column('total_rent', sa.Integer(), nullable=True),
    sa.Column('total_transit', sa.Integer(), nullable=True),
    sa.Column('total_organic', sa.Integer(), nullable=True),
    sa.Column('total_pet', sa.Integer(), nullable=True),
    sa.Column('total_pool', sa.Integer(), nullable=True),
    sa.Column('total_depression', sa.Integer(), nullable=True),
    sa.Column('total_loan', sa.Integer(), nullable=True),
    sa.Column('num_yrs_college', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_index(op.f('ix_player__info_active'), 'player__info', ['active'], unique=False)
    op.create_index(op.f('ix_player__info_job'), 'player__info', ['job'], unique=False)
    op.create_index(op.f('ix_player__info_ready'), 'player__info', ['ready'], unique=False)
    op.create_index(op.f('ix_player__info_turn_num'), 'player__info', ['turn_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player__info_turn_num'), table_name='player__info')
    op.drop_index(op.f('ix_player__info_ready'), table_name='player__info')
    op.drop_index(op.f('ix_player__info_job'), table_name='player__info')
    op.drop_index(op.f('ix_player__info_active'), table_name='player__info')
    op.drop_table('player__info')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_vehicle_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_category'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_picked'), table_name='job')
    op.drop_index(op.f('ix_job_category'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_house_name'), table_name='house')
    op.drop_index(op.f('ix_house_category'), table_name='house')
    op.drop_table('house')
    op.drop_index(op.f('ix_game_finished'), table_name='game')
    op.drop_index(op.f('ix_game_date_started'), table_name='game')
    op.drop_index(op.f('ix_game_date_finished'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_card_text'), table_name='card')
    op.drop_index(op.f('ix_card_regular'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
